### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by noerw** [rockholla/go-lib#1]
Hi @rockholla, could you clarify under what license this code is provided and add a `LICENSE` file?
We'd like to use the yaml marshal code in https://gitea.com/gitea/tea ([context](https://gitea.com/gitea/tea/issues/490#user-content-documenting-the-config-options)), but can't do so without that.

**Comment by rockholla** [comment]
Ah yes, I had meant to do this, so thanks for the reminder. [MIT license added now.](https://github.com/rockholla/go-lib/commit/3f7737a079a5b49837526a79440686c3b6af423c) Hope the lib helps!

**Comment by noerw** [comment]
Thanks!
